### Find All songs
GET http://localhost:5000/api/songs

### Find One song
GET http://localhost:5000/api/songs/1

### Create a song
POST http://localhost:5000/api/songs
Content-Type: application/json

{
  "title": "Example Song Title",
  "artists": [
    "Artist One",
    "Artist Two"
  ],
  "releasedDate": "2024-11-27",
  "duration": "03:25",
  "lyrics": "Example lyrics"
}

### Update a song
PUT http://localhost:5000/api/songs/1
Content-Type: application/json

{
  "title": "Updated Song Title",
  "artists": [
    "Artist One",
    "Artist Two"
  ],
  "releasedDate": "2024-11-27",
  "duration": "03:25",
  "lyrics": "Updated lyrics"
}

### Delete a song
DELETE http://localhost:5000/api/songs/1